### ISSUE TITLE
rButtonTemplate not showing cooldowns/durations on buttons

### ISSUE THREAD

**Issue by joker-119** [zorker/rothui#16]
As title says, cooldowns on actionbar buttons and durations on buffs/debuffs do not show on the icons. 
I can't find anywhere in the theme.lua file where this is disabled, but possibly it needs to be enabled specifically?

**Comment by zorker** [comment]
Can you provide a screenshot?

**Comment by joker-119** [comment]
Playing around alittle I noticed a small issue(bug?).
The addon will display a countdown spiral and text timer on player buffs/debuffs, however if you set the hotkey alpha to 0, it eliminates the text timer on buffs/debuffs aswell.  cooldowns on actionbars will only show the darkened spiral, no text countdown no matter what.

(i should have been more specific in original post, I am referring to the text countdowns on the icons)

Side note: cooldown spiral doesn't appear on player buffs/debuffs, only actionbar cooldowns, which receive no text. Also, there is no alpha control for macro text.

Not sure if this is by design? But I can't find any way to change this in my own layout.

Screenshots; First is with hotkey alpha = 0, second with alpha = 1\
http://imgur.com/a/Hqo4c

**Comment by zorker** [comment]
Galaxy that issue is sth I fixed lately. Config variables where passed by reference in the early versions. Which is no problem if the config is the same for everything. That is why I added the copyTable function. It is needed to make deep copies of all the config tables per button setup. Make sure to use it: https://github.com/zorker/rothui/blob/master/wow7.0/rButtonTemplate_Default/theme.lua#L23
