### ISSUE TITLE
rButtonTemplate not showing cooldown timer on actionbars

### ISSUE THREAD

**Issue by joker-119** [zorker/rothui#20]
So, for some reason you had the aura button duration linked to the actionbar hotkey cfg, I changed that, but the actionbar is not displaying a cooldown timer even though I specified it's alpha = 1. It works on the buff/debuff frames, but not the actionbars.

Note: I'm using the old ActionButtonStyler addon, but I don't think that would make a difference, right?
Also, would there be a way to make buttonTemplate also display countdowns on the target's buff/debuff frames aswell, or is that currently out of the addons scope?

Screenshot: http://imgur.com/a/t6RSi
You can see the buff duration is now displaying a timer, but the actionbar button on cooldown is not, it just has a spiral effect for it's cooldown.

**Comment by zorker** [comment]
That is because player aura buttons have a font string for the duration and they do not have a cooldown spiral.

Action buttons do not have a duration but they have a cooldown spiral. The duration on action buttons comes either from the default Blizzard cooldown spiral number display interface option or by using OmniCC.

I do not style the cooldown frame template. That is part of OmniCC or any other addon alike.
