### ISSUE TITLE
actionbar layout problem

### ISSUE THREAD

**Issue by fafaraway** [zorker/rothui#21]
hi zork, how can I hide some bars
for example, bagbar, I tried "framescale=0", just get errors, or "framescale=0.1", it's still there just really tiny~

**Comment by zorker** [comment]
By using frameVisibility or fader. Either you fade out the bar completly and make it only available on mouseover https://github.com/zorker/rothui/blob/master/wow7.0/rActionBar_Zork/layout.lua#L21 or by using the config attribute frameVisibility (  |-frameVisibility (OPTIONAL), type:STRING, description: visibility state handler. define your own or let rActionBar use the default one.)

Example:

```
local bagbar = {
  framePoint      = { "BOTTOMRIGHT", UIParent, "BOTTOMRIGHT", -5, 5 },
  frameScale      = 1,
  framePadding    = 5,
  buttonWidth     = 32,
  buttonHeight    = 32,
  buttonMargin    = 2,
  numCols         = 6, --number of buttons per column
  startPoint      = "BOTTOMRIGHT", --start postion of first button: BOTTOMLEFT, TOPLEFT, TOPRIGHT, BOTTOMRIGHT
  fader           = fader,
  frameVisibility = "hide"
}
```

The frame visibility can only be "show" or "hide". But there is a twist. You can add macro conditions to show/hide a frame under certain conditions. This is the default bag bar condition: "[petbattle] hide; show" https://github.com/zorker/rothui/blob/master/wow7.0/rActionBar/bars.lua#L21. It will hide the bagbar in petbattle and show it otherwise. You can provide your own visibility config.
