### ISSUE TITLE
weird bug about ractionbar

### ISSUE THREAD

**Issue by fafaraway** [zorker/rothui#56]
only enable rLib + rActionbar + rActionBar_Default

![1](https://user-images.githubusercontent.com/156806/43195534-eaeee66a-9037-11e8-9349-a485893ad09a.jpg)

where is currency tab ???

![2](https://user-images.githubusercontent.com/156806/43195649-4582e95a-9038-11e8-8d23-7ed2d1490d9f.jpg)

disable rLib + rActionbar + rActionBar_Default

![3](https://user-images.githubusercontent.com/156806/43195671-512a432a-9038-11e8-81c7-6ebcd76afadf.jpg)

currency tab is back !!!

what a weird bug 🤣

**Comment by zorker** [comment]
That is probably because I am unregistering events and scripts on Blizzard frames. Not sure though why the default actionbar would affect that tab. :)
https://github.com/zorker/rothui/blob/master/wow8.0/rActionBar/blizzard.lua#L29

I think I found the part in the Blizzard code. The token UI is nowhere else loaded. Will give it a run later. :)
https://github.com/tomrus88/BlizzardInterfaceCode/blob/master/Interface/FrameXML/MainMenuBar.lua#L97
