### ISSUE TITLE
Can framefader support LibActionButtons 1.0

### ISSUE THREAD

**Issue by dwWei** [zorker/rothui#69]
Can framefader support LibActionButtons 1.0

**Comment by dwWei** [comment]
SpellFlyout is not supported

**Comment by zorker** [comment]
Issue is fixed with this commit: https://github.com/zorker/rothui/commit/1fb0b61d979fffc2002355e6ceb4cf6c526179fa
I provided a test addon rBarTest to show it.
Drag a flyout button on your first actionbar button in your main actionbar and press alt to load the LibActionButton bar. The addon is just to show how it works. Example: https://imgur.com/a/Qc7mpMK
